server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafyweb?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    token:
      secret-key: ${SPRING_JWT_SECRET_KEY:}
    access:
        expiration: 1000
    refresh:
        expiration: 10000

oauth2:
  client:
    registration:
      kakao:
        client-id: a6418c103857bee3f2d97da6886ed1d7
        client-secret: secret
        redirect-uri: http://localhost:8080/oauth2/callback/kakao
        scope: profile_nickname, account_email
      google:
        client-id: a
        client-secret: b
        redirect-uri: http://localhost:8080/oauth2/callback/google
        scope: profile, email
      naver:
        client-id: a
        client-secret: b
        redirect-uri: http://localhost:8080/oauth2/callback/naver
        scope: profile, email
    provider:
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        mappings:
          id: id
          email: kakao_account.email
          name: properties.nickname
          imageUrl: properties.profile_image
      google:
        authorization-uri: https://accounts.google.com/o/oauth2/auth
        token-uri: https://oauth2.googleapis.com/token
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        mappings:
          id: sub
          email: email
          name: name
          imageUrl: picture
      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        mappings:
          id: response.id
          email: response.email
          name: response.name
          imageUrl: response.profile_image

mybatis:
  type-aliases-package: com.ssafy.web.*.model
  mapper-locations: classpath:mapper/**/*.xml
